INSERT INTO `events_region` (id, name) VALUES (8, 'Abitibi-Témiscamingue');
INSERT INTO `events_region` (id, name) VALUES (1, 'Bas-Saint-Laurent');
INSERT INTO `events_region` (id, name) VALUES (3, 'Capitale-Nationale');
INSERT INTO `events_region` (id, name) VALUES (17, 'Centre-du-Québec');
INSERT INTO `events_region` (id, name) VALUES (12, 'Chaudière-Appalaches');
INSERT INTO `events_region` (id, name) VALUES (9, 'Côte-Nord');
INSERT INTO `events_region` (id, name) VALUES (5, 'Estrie');
INSERT INTO `events_region` (id, name) VALUES (11, 'Gaspésie–Îles-de-la-Madeleine');
INSERT INTO `events_region` (id, name) VALUES (14, 'Lanaudière');
INSERT INTO `events_region` (id, name) VALUES (15, 'Laurentides');
INSERT INTO `events_region` (id, name) VALUES (13, 'Laval');
INSERT INTO `events_region` (id, name) VALUES (4, 'Mauricie');
INSERT INTO `events_region` (id, name) VALUES (16, 'Montérégie');
INSERT INTO `events_region` (id, name) VALUES (6, 'Montréal');
INSERT INTO `events_region` (id, name) VALUES (10, 'Nord-du-Québec');
INSERT INTO `events_region` (id, name) VALUES (7, 'Outaouais');
INSERT INTO `events_region` (id, name) VALUES (2, 'Saguenay–Lac-Saint-Jean');
INSERT INTO `events_region` (id, name) VALUES (99, 'Autre province, état, pays');
